/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrayerTimesUploadPrayerTimesRouteImport } from './routes/prayer-times/upload-prayer-times'
import { Route as PrayerTimesTestPrayerTimesRouteImport } from './routes/prayer-times/test-prayer-times'
import { Route as PrayerTimesPrayerIqamaRouteImport } from './routes/prayer-times/prayer-iqama'
import { Route as PrayerTimesMosquePrayerTimesRouteImport } from './routes/prayer-times/mosque-prayer-times'
import { Route as MosqueMosqueDetailsRouteImport } from './routes/mosque/mosque-details'
import { Route as EventsListEventsRouteImport } from './routes/events/list-events'
import { Route as EventsCreateEventRouteImport } from './routes/events/create-event'
import { Route as MosqueMosqueConfigIndexRouteImport } from './routes/mosque/mosque-config/index'
import { Route as MosqueMosqueConfigConfigIdRouteImport } from './routes/mosque/mosque-config/$configId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerTimesUploadPrayerTimesRoute =
  PrayerTimesUploadPrayerTimesRouteImport.update({
    id: '/prayer-times/upload-prayer-times',
    path: '/prayer-times/upload-prayer-times',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrayerTimesTestPrayerTimesRoute =
  PrayerTimesTestPrayerTimesRouteImport.update({
    id: '/prayer-times/test-prayer-times',
    path: '/prayer-times/test-prayer-times',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrayerTimesPrayerIqamaRoute = PrayerTimesPrayerIqamaRouteImport.update({
  id: '/prayer-times/prayer-iqama',
  path: '/prayer-times/prayer-iqama',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerTimesMosquePrayerTimesRoute =
  PrayerTimesMosquePrayerTimesRouteImport.update({
    id: '/prayer-times/mosque-prayer-times',
    path: '/prayer-times/mosque-prayer-times',
    getParentRoute: () => rootRouteImport,
  } as any)
const MosqueMosqueDetailsRoute = MosqueMosqueDetailsRouteImport.update({
  id: '/mosque/mosque-details',
  path: '/mosque/mosque-details',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsListEventsRoute = EventsListEventsRouteImport.update({
  id: '/events/list-events',
  path: '/events/list-events',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCreateEventRoute = EventsCreateEventRouteImport.update({
  id: '/events/create-event',
  path: '/events/create-event',
  getParentRoute: () => rootRouteImport,
} as any)
const MosqueMosqueConfigIndexRoute = MosqueMosqueConfigIndexRouteImport.update({
  id: '/mosque/mosque-config/',
  path: '/mosque/mosque-config/',
  getParentRoute: () => rootRouteImport,
} as any)
const MosqueMosqueConfigConfigIdRoute =
  MosqueMosqueConfigConfigIdRouteImport.update({
    id: '/mosque/mosque-config/$configId',
    path: '/mosque/mosque-config/$configId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/create-event': typeof EventsCreateEventRoute
  '/events/list-events': typeof EventsListEventsRoute
  '/mosque/mosque-details': typeof MosqueMosqueDetailsRoute
  '/prayer-times/mosque-prayer-times': typeof PrayerTimesMosquePrayerTimesRoute
  '/prayer-times/prayer-iqama': typeof PrayerTimesPrayerIqamaRoute
  '/prayer-times/test-prayer-times': typeof PrayerTimesTestPrayerTimesRoute
  '/prayer-times/upload-prayer-times': typeof PrayerTimesUploadPrayerTimesRoute
  '/mosque/mosque-config/$configId': typeof MosqueMosqueConfigConfigIdRoute
  '/mosque/mosque-config/': typeof MosqueMosqueConfigIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/create-event': typeof EventsCreateEventRoute
  '/events/list-events': typeof EventsListEventsRoute
  '/mosque/mosque-details': typeof MosqueMosqueDetailsRoute
  '/prayer-times/mosque-prayer-times': typeof PrayerTimesMosquePrayerTimesRoute
  '/prayer-times/prayer-iqama': typeof PrayerTimesPrayerIqamaRoute
  '/prayer-times/test-prayer-times': typeof PrayerTimesTestPrayerTimesRoute
  '/prayer-times/upload-prayer-times': typeof PrayerTimesUploadPrayerTimesRoute
  '/mosque/mosque-config/$configId': typeof MosqueMosqueConfigConfigIdRoute
  '/mosque/mosque-config': typeof MosqueMosqueConfigIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/create-event': typeof EventsCreateEventRoute
  '/events/list-events': typeof EventsListEventsRoute
  '/mosque/mosque-details': typeof MosqueMosqueDetailsRoute
  '/prayer-times/mosque-prayer-times': typeof PrayerTimesMosquePrayerTimesRoute
  '/prayer-times/prayer-iqama': typeof PrayerTimesPrayerIqamaRoute
  '/prayer-times/test-prayer-times': typeof PrayerTimesTestPrayerTimesRoute
  '/prayer-times/upload-prayer-times': typeof PrayerTimesUploadPrayerTimesRoute
  '/mosque/mosque-config/$configId': typeof MosqueMosqueConfigConfigIdRoute
  '/mosque/mosque-config/': typeof MosqueMosqueConfigIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/create-event'
    | '/events/list-events'
    | '/mosque/mosque-details'
    | '/prayer-times/mosque-prayer-times'
    | '/prayer-times/prayer-iqama'
    | '/prayer-times/test-prayer-times'
    | '/prayer-times/upload-prayer-times'
    | '/mosque/mosque-config/$configId'
    | '/mosque/mosque-config/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events/create-event'
    | '/events/list-events'
    | '/mosque/mosque-details'
    | '/prayer-times/mosque-prayer-times'
    | '/prayer-times/prayer-iqama'
    | '/prayer-times/test-prayer-times'
    | '/prayer-times/upload-prayer-times'
    | '/mosque/mosque-config/$configId'
    | '/mosque/mosque-config'
  id:
    | '__root__'
    | '/'
    | '/events/create-event'
    | '/events/list-events'
    | '/mosque/mosque-details'
    | '/prayer-times/mosque-prayer-times'
    | '/prayer-times/prayer-iqama'
    | '/prayer-times/test-prayer-times'
    | '/prayer-times/upload-prayer-times'
    | '/mosque/mosque-config/$configId'
    | '/mosque/mosque-config/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsCreateEventRoute: typeof EventsCreateEventRoute
  EventsListEventsRoute: typeof EventsListEventsRoute
  MosqueMosqueDetailsRoute: typeof MosqueMosqueDetailsRoute
  PrayerTimesMosquePrayerTimesRoute: typeof PrayerTimesMosquePrayerTimesRoute
  PrayerTimesPrayerIqamaRoute: typeof PrayerTimesPrayerIqamaRoute
  PrayerTimesTestPrayerTimesRoute: typeof PrayerTimesTestPrayerTimesRoute
  PrayerTimesUploadPrayerTimesRoute: typeof PrayerTimesUploadPrayerTimesRoute
  MosqueMosqueConfigConfigIdRoute: typeof MosqueMosqueConfigConfigIdRoute
  MosqueMosqueConfigIndexRoute: typeof MosqueMosqueConfigIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-times/upload-prayer-times': {
      id: '/prayer-times/upload-prayer-times'
      path: '/prayer-times/upload-prayer-times'
      fullPath: '/prayer-times/upload-prayer-times'
      preLoaderRoute: typeof PrayerTimesUploadPrayerTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-times/test-prayer-times': {
      id: '/prayer-times/test-prayer-times'
      path: '/prayer-times/test-prayer-times'
      fullPath: '/prayer-times/test-prayer-times'
      preLoaderRoute: typeof PrayerTimesTestPrayerTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-times/prayer-iqama': {
      id: '/prayer-times/prayer-iqama'
      path: '/prayer-times/prayer-iqama'
      fullPath: '/prayer-times/prayer-iqama'
      preLoaderRoute: typeof PrayerTimesPrayerIqamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-times/mosque-prayer-times': {
      id: '/prayer-times/mosque-prayer-times'
      path: '/prayer-times/mosque-prayer-times'
      fullPath: '/prayer-times/mosque-prayer-times'
      preLoaderRoute: typeof PrayerTimesMosquePrayerTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mosque/mosque-details': {
      id: '/mosque/mosque-details'
      path: '/mosque/mosque-details'
      fullPath: '/mosque/mosque-details'
      preLoaderRoute: typeof MosqueMosqueDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/list-events': {
      id: '/events/list-events'
      path: '/events/list-events'
      fullPath: '/events/list-events'
      preLoaderRoute: typeof EventsListEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/create-event': {
      id: '/events/create-event'
      path: '/events/create-event'
      fullPath: '/events/create-event'
      preLoaderRoute: typeof EventsCreateEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mosque/mosque-config/': {
      id: '/mosque/mosque-config/'
      path: '/mosque/mosque-config'
      fullPath: '/mosque/mosque-config/'
      preLoaderRoute: typeof MosqueMosqueConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mosque/mosque-config/$configId': {
      id: '/mosque/mosque-config/$configId'
      path: '/mosque/mosque-config/$configId'
      fullPath: '/mosque/mosque-config/$configId'
      preLoaderRoute: typeof MosqueMosqueConfigConfigIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsCreateEventRoute: EventsCreateEventRoute,
  EventsListEventsRoute: EventsListEventsRoute,
  MosqueMosqueDetailsRoute: MosqueMosqueDetailsRoute,
  PrayerTimesMosquePrayerTimesRoute: PrayerTimesMosquePrayerTimesRoute,
  PrayerTimesPrayerIqamaRoute: PrayerTimesPrayerIqamaRoute,
  PrayerTimesTestPrayerTimesRoute: PrayerTimesTestPrayerTimesRoute,
  PrayerTimesUploadPrayerTimesRoute: PrayerTimesUploadPrayerTimesRoute,
  MosqueMosqueConfigConfigIdRoute: MosqueMosqueConfigConfigIdRoute,
  MosqueMosqueConfigIndexRoute: MosqueMosqueConfigIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
